import { Inter } from "next/font/google";

import Header from "@/components/Header";
import Footer from "@/components/Footer";
import styles from "@/app/styles.module.css";

import "@/styles/reset.css";
import "@/styles/global.css";

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={inter.className}>
      <body className={styles.container}>
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}

export const metadata = {
  title: "Blog Page",
  description: "Generated by create next app",
};
